// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5wOMdM-tqBBM7dpOCeZQo4lKJISrZ350',
    appId: '1:263667142485:web:b38d1cf6a08c0450ab29dc',
    messagingSenderId: '263667142485',
    projectId: 'rit-placement-cell',
    authDomain: 'rit-placement-cell.firebaseapp.com',
    storageBucket: 'rit-placement-cell.appspot.com',
    measurementId: 'G-XCLL7RVKDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdWmsk5bNK6IqaiRVGOzihYcU2mp-9-xo',
    appId: '1:263667142485:android:97837ac50586d06cab29dc',
    messagingSenderId: '263667142485',
    projectId: 'rit-placement-cell',
    storageBucket: 'rit-placement-cell.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9wrtLON8VrYg1fp67hKO8f0JiuHCoUJc',
    appId: '1:263667142485:ios:0d5bf43a4676072eab29dc',
    messagingSenderId: '263667142485',
    projectId: 'rit-placement-cell',
    storageBucket: 'rit-placement-cell.appspot.com',
    iosClientId: '263667142485-su3s1fckvn2gpfg1mdhhvp9stl27oco0.apps.googleusercontent.com',
    iosBundleId: 'com.example.company',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9wrtLON8VrYg1fp67hKO8f0JiuHCoUJc',
    appId: '1:263667142485:ios:5b526c75e42b4074ab29dc',
    messagingSenderId: '263667142485',
    projectId: 'rit-placement-cell',
    storageBucket: 'rit-placement-cell.appspot.com',
    iosClientId: '263667142485-ru8ct03pnp442jadi43h25ur6sae0707.apps.googleusercontent.com',
    iosBundleId: 'com.example.company.RunnerTests',
  );
}
